language: node_js
node_js:
  - '6'
sudo: true
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install --non-interactive --frozen-lockfile
script:
  - yarn lint:hbs
  - yarn lint:js
  - yarn test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - PERCY_PROJECT=opensource-challenge/opensource-challenge-client
    - secure: PkKoqLSXvLiCmD8dzPVw/klJ6QfT4y4Unl6sWwDZZH5mrGDT1/vqdR8lS4G9X65ICQg27rRVwly6tv5o+sXQFQlXMpEiGO7RXncIHHMRD/sF3PTnGVopyQq1jFHqFEHOAbKXvwVRuIilUR+OGhdyLk6NHt+/9MgHSR2Y0+B1XxheC6eltRUsdzYCQiT7U5WBaeGpIznkCLithtc7VsZudbnsR3iVuKVvpKXOQ5MJabyrS3lR7onfyzRmqwQKx7Mc0DaLFalO0UnwO3z09K/ER30nzrHTR9hNEh8DUItsxELQKGU4AxOw3AsexJkbhpwdNSt3+4F5uOh0+YnqMYcn7EPXv4OWVK6bNpe/UUxppuwTSSdrnbM1EB79kZn5jyZLrC0Q6x+X1vF70mlz/GYQ3IySVk1zKny7GkxpCnmjoAM90CzK9NoqRhYYDKBegWeRXSGCG4P5nqyo73ic1JLmnOTWw/IYb97JEFXc1vIySTqleqUj+q6DHleJ+6Fls6IBUCMr3HXsj5VXfnwSlxRMB3gu9RgNQIr4Z8UK7zsWTgvmK6ZOzabeIyf74kMgrbmh8rJSY4vDEHnwxfq2DyVHc4/XjTVeJF40WgAdu2XjB75MefrZLLrTDDhdxCzL1vBiIWdpWsswp3gMkdCJaJ8EsThh7Luy5G6OreJb6Ibo3yw=
  matrix:
    - COVERAGE=true CODECLIMATE_REPO_TOKEN=9e087f07cf44e07584de87390bc3e55de61e1523afe675df9c8f4d6ba7fba38b
